### ISSUE TITLE
[Добавление функционала] Отдельная вкладка для избранных стримеров

### ISSUE THREAD

**Issue by MercyMyWaifu** [Eviloid/plugin.video.evld.goodgame.ru#1]
Можно ли сделать отдельную вкладку со стримами, которые находятся в избранном?

**Comment by Eviloid** [comment]
А вот не понятно. Я использую goodgame [API](http://api2.goodgame.ru/apigility/documentation). И в нём не нашел как получить **Избранное**. Хотя в [описании авторизации](https://github.com/GoodGame/API/blob/master/Streams/v2/authentication.md) есть упоминание:
> user.favorites - необходим для получения списка всех избранных стримов пользователя

Так я для себя делал - то забил на это дело. Попробую ещё покопать в этом направлении.

Спасибо.

**Comment by MercyMyWaifu** [comment]
Спасибо тебе, что делаешь. А хотя бы что-то типа: вводишь название канала и плагин его открывает, некоторые стримеры в скрытом просто стримят и нет их в общем списке.

**Comment by Eviloid** [comment]
Сделал я вариант. В настройках включить опцию "Избранные стримы" и ввести идентификаторы нужных каналов через запятую. Ид канала виден в браузере в url:

goodgame.ru/channel/**тут_ид**/#autoplay

Надеюсь устроит такое решение.

Если API допилят - то переделаю уже по-человечески.

**Comment by MercyMyWaifu** [comment]
Спасибо. Да, вполне норм решение.
